CREATE TABLE `TBL_MOA_PRD_MAIN` (
  `SEQ` int(11) NOT NULL AUTO_INCREMENT,
  `M_MOA_CODE` varchar(10) DEFAULT NULL COMMENT 'Moa Mart Code',
  `M_POS_REGCODE` int(11) DEFAULT NULL COMMENT 'POS-link code: Mart code registered on POS system',
  `P_CODE` int(11) DEFAULT NULL COMMENT 'Product code from POS',
  `P_NAME` varchar(50) DEFAULT NULL COMMENT 'Product name from POS',
  `P_CAT_CODE` int(11) DEFAULT NULL,
  `P_CAT` varchar(50) DEFAULT NULL COMMENT 'Product category from POS - different from individual marts.',
  `P_MCAT_CODE` int(11) DEFAULT NULL,
  `P_MCAT` varchar(50) DEFAULT NULL,
  `P_CAT_SEQNO` int(11) DEFAULT NULL,
  `P_CAT_SUB` varchar(50) DEFAULT NULL,
  `P_UNIT` varchar(50) DEFAULT NULL COMMENT 'Product unity (and qty)',
  `P_BARCODE` varchar(20) DEFAULT NULL COMMENT 'Product barcode: EAN-13/EAN-8 Compliant',
  `P_LIST_PRICE` float DEFAULT NULL COMMENT 'Product list price',
  `P_PROVIDER` varchar(60) DEFAULT NULL COMMENT 'Product manufacturer or distributor name',
  `P_SALE_PRICE` float DEFAULT NULL COMMENT 'Sale price',
  `P_SALE_TITLE` varchar(60) DEFAULT NULL COMMENT 'Sale program title',
  `P_MTIME` datetime DEFAULT NULL COMMENT 'Latest update time from POS',
  `P_TAX_TYPE` int(11) DEFAULT NULL,
  `P_INV_TYPE` int(11) DEFAULT NULL COMMENT 'Inventory manage type',
  `P_REG_COUNT` int(11) DEFAULT NULL COMMENT 'Number of product registration',
  `P_IMG` varchar(3000) DEFAULT NULL COMMENT 'Product image path: JSON structure for multiple images',
  `IS_CUSTOM_IMAGE` varchar(1) DEFAULT 'N',
  `P_TAGS` varchar(3000) DEFAULT NULL COMMENT 'Hastags ',
  `P_STATUS` varchar(1) DEFAULT NULL COMMENT 'Product status: ‘A’ - Active, ‘C’ - Cancelled/Hidden ',
  `P_MIN_STOCK` int(11) DEFAULT 0 COMMENT 'Value min stock default. when product have stock under show out of stock',
  `P_MIN_STOCK_DEFAULT` int(11) DEFAULT 0 COMMENT 'Value min stock default. when product have stock under show out of stock',
  `P_USE_MAXQTY_BRGN` varchar(1) DEFAULT 'N' COMMENT 'Custom use or not use maxqty BRGN',
  `P_MAXQTY_BRGN` int(4) DEFAULT NULL,
  `P_MAXQTY_BRGN_DEFAULT` int(4) DEFAULT NULL,
  `C_TIME` datetime DEFAULT current_timestamp() COMMENT 'Timestamp of data creation ',
  `C_ID` varchar(45) DEFAULT NULL COMMENT 'Account who creates data ',
  `M_TIME` datetime DEFAULT current_timestamp() COMMENT 'Timesamp of lastest data modification ',
  `M_ID` varchar(45) DEFAULT NULL COMMENT 'Account who modified data last ',
  `P_USE_MAXQTY_PD` varchar(1) DEFAULT 'N',
  `P_VALUE_MAXQTY_PD` int(4) DEFAULT NULL,
  `P_USE_MINQTY_PD` varchar(1) DEFAULT 'N',
  `P_VALUE_MINQTY_PD` int(4) DEFAULT NULL,
  PRIMARY KEY (`SEQ`),
  KEY `M_MOA_CODE` (`M_MOA_CODE`,`P_CODE`,`P_NAME`,`P_BARCODE`),
  KEY `IDX_MART_SEQ` (`M_POS_REGCODE`),
  KEY `M_POS_REGCODE` (`M_POS_REGCODE`,`P_CODE`,`P_BARCODE`)
) ENGINE=InnoDB

CREATE TABLE `TBL_MOA_MART_SYNC` (
  `SEQ` int NOT NULL AUTO_INCREMENT,
  `M_MOA_CODE` varchar(45) DEFAULT NULL,
  `M_NAME` varchar(45) DEFAULT NULL,
  `M_GROUP` varchar(45) DEFAULT NULL,
  `LAST_DATE_SYNC` datetime DEFAULT NULL,
  `SHOULD_DOWN_FILE` char(1) DEFAULT 'N',
  PRIMARY KEY (`SEQ`)
) ENGINE=InnoDB
